version: "2"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"

  postgres_test:
    image: postgres:latest
    ports:
      - "5433:5432"

  postgres_prod:
    image: postgres:latest
    ports:
      - "5434:5432"
    # environment:
    #   POSTGRES_DB: Farmacia_production
    #   POSTGRES_USER: Farmacia
    #   POSTGRES_PASSWORD: postgres
    #   FARMACIA_DATABASE_PASSWORD: postgres
